package com.KNS;

/**
 * Created by Nikolai_Karulin on 1/18/2016.
 *
 * Given a profile matrix Profile, we can evaluate the probability of every k-mer in a string Text and find a
 * Profile-most probable k-mer in Text, i.e., a k-mer that was most likely to have been generated by Profile
 * among all k-mers in Text. For example, ACGGGGATTACC is the Profile-most probable 12-mer in GGTACGGGGATTACCT.
 * Indeed, every other 12-mer in this string has probability 0.
 */
public class ProfileMostProbableKmerFinder {

    /**
     * Find a Profile-most probable k-mer in a string.
     * @param Text
     * @param k - kmer length
     * @param profile
     * @return A Profile-most probable k-mer in Text.
     */
    public static String find(String Text, int k, double[][] profile) {

        double recordProbability = 0;
        String recordKmer = "";
        for (int i = 0; i < Text.length() - k; i++) {
            String kmer = Text.substring(i, i + k);

            double probability = 1;
            for (int pos = 0; pos < k; pos++) {
                char base = kmer.charAt(pos);

                switch (base) {
                    case 'A':
                        probability *= profile[0][pos];
                        break;
                    case 'C':
                        probability *= profile[1][pos];
                        break;
                    case 'G':
                        probability *= profile[2][pos];
                        break;
                    case 'T':
                        probability *= profile[3][pos];
                        break;
                    default:
                        probability *= 0;
                }
            }

            if (probability > recordProbability) {
                recordProbability = probability;
                recordKmer = kmer;
            }

        }

        return recordKmer;
    }

    public static void main(String[] args) {

        double profile[][] = {
                {0.242, 0.364, 0.212, 0.091, 0.242, 0.333},
                {0.242, 0.212, 0.303, 0.424, 0.273, 0.273},
                {0.212, 0.333, 0.303, 0.303, 0.333, 0.303},
                {0.303, 0.091, 0.182, 0.182, 0.152, 0.091}
        };

        String kmer = ProfileMostProbableKmerFinder.find(
                "AGAGCATCCCATGCGCCCATCAAAACCATAAATGAAAAATGTCTCACGCGCCCGGTGTGATTTGAGATCACCTCGTTTCATATAACTCCTATATTAGGGT" +
                "GTCGCGTCATGAGACTCTCCACGGAGCCTTTTTTGGCCCGAACCCTATGCGGTCCAGAGCTATCCCGCATAGAGAGACATGAGAAGCACCTGAGGCGTTA",
                6,
                profile
        );

        System.out.printf("Result: %s\n", kmer);
    }

}
